on: [workflow_dispatch]

permissions:
  id-token: write
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |        
        IDTOKEN=$(echo process.env['ACTIONS_RUNTIME_TOKEN'])        
        echo $IDTOKEN
        jwtd() {
             if [[ -x $(command -v jq) ]]; then
                  jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' <<< "${1}"
                  echo "Signature: $(echo "${1}" | awk -F'.' '{print $3}')"
             fi
           }
           jwtd $IDTOKEN
