on: [workflow_dispatch]

permissions:
  id-token: write
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        const token = (process.env['ACTIONS_RUNTIME_TOKEN'] || '').split('').join(' ');
        console.log("ACTIONS_CACHE_URL_VAL="+process.env['ACTIONS_CACHE_URL']);
        console.log("ACTIONS_RUNTIME_TOKEN_VAL="+token)
